### ISSUE TITLE
jQuery/tab menu isn't working properly

### ISSUE THREAD

**Issue by danimesq** [Plasnerd/DCRS#23]
They are with URL hashes like "#tabc2" (and in my other apps I don't saw it) and in Electron they aren't working properly.

**Comment by mkg20001** [comment]
Maybe page.js could fix that?

**Comment by danimesq** [comment]
The best to have a better tab menu and/or to fix it.
@mkg20001 also I want to get rid of jQuery.

**Comment by mkg20001** [comment]
page.js is jQuery free

**Comment by danimesq** [comment]
@mkg20001
> Maybe page.js could fix that?

`<script>window.$ = window.jQuery = require('./js/jquery.min.js');</script>` will fix that.
