### ISSUE TITLE
Onload, if not in Electron: redirect to homepage

### ISSUE THREAD

**Issue by danimesq** [Plasnerd/DCRS#35]

**Comment by mkg20001** [comment]
What do you mean?

**Comment by danimesq** [comment]
I'm talking about browser/clearnet visitors. When they try to enter the url that need to be DCRSUI-exclusive, they will be redirected.

**Comment by danimesq** [comment]
@mkg20001 Sorry. I fixed the title.

**Comment by danimesq** [comment]
What do you think about?

**Comment by danimesq** [comment]
@mkg20001 thanks.
